spring.application.name=SkillSwap

server.tomcat.threads.max=300


#spring.datasource.url=jdbc:mysql:///skillswap
#spring.datasource.username=root
#spring.datasource.password=root
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.url=jdbc:mysql://hopper.proxy.rlwy.net:48211/railway
spring.datasource.username=root
spring.datasource.password=lspGBBgfQEhnhlUysZaemGdpWrOPtUiB
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#trolley.proxy.rlwy.net:36334
# ===============================
# JPA / HIBERNATE CONFIGURATION
# ===============================
# 'update' automatically creates/updates tables based on your Java Entities
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#server.port=4041

#spring.mvc.view.prefix=/WEB-INF/pages
#spring.mvc.view.suffix=.jsp


## Base64 encoded 256-bit secret (VERY IMPORTANT)
jwt.secret=REPLACE_WITH_BASE64_256_BIT_SECRET

# Access token expiry (30 minutes)
jwt.access.expiration=1800000

# Refresh token expiry (180 days)
jwt.refresh.expiration=15552000000

#server.servlet.context-path=/SkillSwap


logging.level.org.springframework.security=DEBUG

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=profile,email


gemini.api.key=AIzaSyCSMJY2Dso80usWXroPHuQaFH2E0SqsssY



spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=skillswaparena@gmail.com
spring.mail.password=mzap aitj myce linm

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com


#server.address=0.0.0.0

server.port=${5051}
